/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testande;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author marku
 */
public class Inlogg extends javax.swing.JFrame {

    /**
     * Creates new form Inlogg
     */
     public Inlogg() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblFelMeddelande.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmail = new javax.swing.JLabel();
        jLabelPw = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        lblFelMeddelande = new javax.swing.JLabel();
        jPasswordFieldPw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelEmail.setText("Email:");

        jLabelPw.setText("Password:");

        jButtonLogin.setText("Logga in");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonExit.setText("Avsluta");

        lblFelMeddelande.setForeground(java.awt.Color.red);

        jPasswordFieldPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPwKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButtonLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPw)
                            .addComponent(jLabelEmail))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordFieldPw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPw)
                    .addComponent(jPasswordFieldPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogin)
                .addGap(28, 28, 28)
                .addComponent(jButtonExit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        lblFelMeddelande.setText("");
        String epost = jTextFieldEmail.getText();
        String losenord = new String(jPasswordFieldPw.getPassword());

        if (Validering.textFaltHarVarde(jTextFieldEmail) && Validering.textFaltHarVarde(jPasswordFieldPw)) {
            try {
                String fraga = "SELECT Losenord from ANVANDARE where Epost = '" + epost + "'";
                String fraga2 = "SELECT AnvandarID from ANVANDARE where Epost = '" + epost + "'";

                String losenord2 = GetQuery(fraga);
                String anvandarID = GetQuery(fraga2);

                if (losenord.equals(losenord2)) {
                    dispose();
                    new AnvandarStartsida(epost).setVisible(true);

                } else {
                    lblFelMeddelande.setText("Felaktigt användarnamn eller lösenord");
                }
            } catch (Exception ex) {
                lblFelMeddelande.setText("Något gick fel");
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldPwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPwKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lblFelMeddelande.setText("");
            String epost = jTextFieldEmail.getText();
            String losenord = new String(jPasswordFieldPw.getPassword());

            if (Validering.textFaltHarVarde(jTextFieldEmail) && Validering.textFaltHarVarde(jPasswordFieldPw)) {
                try {
                    String fraga = "SELECT Losenord from ANVANDARE where Epost = '" + epost + "'";
                    String fraga2 = "SELECT AnvandarID from ANVANDARE where Epost = '" + epost + "'";

                    String losenord2 = GetQuery(fraga);
                    String anvandarID = GetQuery(fraga2);

                    if (losenord.equals(losenord2)) {
                        dispose();
                        new AnvandarStartsida(epost).setVisible(true);

                    } else {
                        lblFelMeddelande.setText("Felaktigt användarnamn eller lösenord");
                    }
                } catch (Exception ex) {
                    lblFelMeddelande.setText("Något gick fel");
                }
            }
        }
    }//GEN-LAST:event_jPasswordFieldPwKeyPressed

    public String GetQuery(String s) {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String losen = null;
        try {
            String query = s;
            ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                losen = rs.getString(1);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return losen;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPw;
    private javax.swing.JPasswordField jPasswordFieldPw;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JLabel lblFelMeddelande;
    // End of variables declaration//GEN-END:variables
}
