package testande;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Random;
import testande.AnvandarStartsida;

public class skapaAnvandare extends javax.swing.JFrame {
    
    String epost;
    private String char_list = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";

    /**
     * Creates new form skapaAnvandare
     */
    public skapaAnvandare() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public skapaAnvandare(String e) {
        initComponents();
        this.setLocationRelativeTo(null);
        epost = e;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                                           

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String fornamn = jTextFieldFirstname.getText();
        String efternamn = jTextFieldLastname.getText();
        String mail = jTextFieldEmail.getText();
        String telnr = jTextFieldPhone.getText();
        String losenord = jTextFieldPw.getText();
        boolean adminstatus = cboxAdministrator.isSelected(); 
        
        String admin = "F";
        
        if(adminstatus){
            admin = "T";
        }
        
        
        if (Validering.baraBokstaver(jTextFieldFirstname) && Validering.textFaltHarVarde(jTextFieldFirstname)){
            if (Validering.baraBokstaver(jTextFieldLastname) && Validering.textFaltHarVarde(jTextFieldLastname)){
                if (Validering.korrektEmail(mail)){
                    if (Validering.korrektTelnr(jTextFieldPhone)){
                        if (Validering.korrektLosenord(jTextFieldPw)){
                            String id = GetAutoId("SELECT MAX(ANVANDARID) FROM ANVANDARE");
                            String fraga = "INSERT into ANVANDARE values ('" + id + "', '" + fornamn + "', '" + efternamn +
                                    "', '" + mail + "', '" + telnr + "', '" + losenord + "', '" + admin + "','-','T')";
                            
                            skapaAnvandare(fraga);
                            
                            JOptionPane.showMessageDialog(null, "Användare tillagd");
                            
                            emptyBoxes();
                        }
                    }
                    
                }
                
            }
        }
    }                                           

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.dispose();
        new AnvandarStartsida(epost).setVisible(true);
    }                                           
                         
    
    private void skapaAnvandare(String Q){
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
	try {
	    String query= Q;
	    ps=connection.prepareStatement(query);
	    ps.executeUpdate();
	} catch (SQLException e) {
	    System.out.println(e);
	}
    }
    
    private void emptyBoxes(){
        jTextFieldFirstname.setText(null);
        jTextFieldLastname.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldPhone.setText(null);
        jTextFieldPw.setText(null);
        cboxAdministrator.setSelected(false);
    }
    
            public String GetAutoId(String o) {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        int idNy = 1;
        try {
            String query = o;
            ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                idNy = rs.getInt(1);
            }

        } catch (Exception ex) {
            System.out.println("Internt felmeddelande: " + ex);
        }

        idNy = idNy + 1;

        return Integer.toString(idNy);
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFirstname = new javax.swing.JLabel();
        jLabelLastname = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhonenmbr = new javax.swing.JLabel();
        jLabelPw = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldPw = new javax.swing.JTextField();
        cboxAdministrator = new javax.swing.JCheckBox();
        btnLaggTill = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFirstname.setText("Förnamn:");

        jLabelLastname.setText("Efternamn:");

        jLabelEmail.setText("Mailadress:");

        jLabelPhonenmbr.setText("Telefonnummer:");

        jLabelPw.setText("Lösenord:");

        cboxAdministrator.setText("Administratör");

        btnLaggTill.setText("Lägg till");

        btnTillbaka.setText("Tillbaka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPhonenmbr)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelLastname)
                                    .addComponent(jLabelFirstname)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabelPw)))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFirstname)
                            .addComponent(jTextFieldLastname)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldPw, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(cboxAdministrator)
                        .addGap(116, 116, 116)
                        .addComponent(btnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstname)
                    .addComponent(jTextFieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastname)
                    .addComponent(jTextFieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhonenmbr)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPw)
                    .addComponent(jTextFieldPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxAdministrator))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JCheckBox cboxAdministrator;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelLastname;
    private javax.swing.JLabel jLabelPhonenmbr;
    private javax.swing.JLabel jLabelPw;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPw;
    // End of variables declaration//GEN-END:variables
}
