/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agent;

import Validering.Validering;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;



/**
 *
 * @author Vincent
 */
public class SokAliensMellan2Datum extends javax.swing.JFrame {

    /**
     * Creates new form SokAliensMellan2Datum
     */
    private InfDB idb;
    
    
    public SokAliensMellan2Datum(InfDB idb) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDatum1 = new javax.swing.JTextField();
        txtDatum2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultat = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDatum1.setText("2008-01-30");

        txtDatum2.setText("2010-06-30");

        jLabel1.setText("Från datum:");

        jLabel2.setText("Till datum:");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        txtAreaResultat.setColumns(20);
        txtAreaResultat.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultat);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(btnSok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatum2))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSok)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void StringToSQLDateExample(){

        String str1=txtDatum1.getText();
        Date date1 = Date.valueOf(str1);//converting string into sql date.
        String str2 = txtDatum2.getText();
        Date date2 = Date.valueOf(str2);
        
        System.out.println(date1);
        System.out.println(date2);
        
        String fraga =("SELECT ALIEN_ID, NAMN FROM ALIEN WHERE REGISTRERINGSDATUM BETWEEN " + date1 + " AND " + date2 + ";");
        System.out.println(fraga);
        
        if(Validering.textNotEmpty(txtDatum1) && Validering.textNotEmpty(txtDatum2)){
            try{
                
                ArrayList<HashMap<String, String>> sokResultat = idb.fetchRows("SELECT ALIEN_ID, NAMN FROM ALIEN WHERE REGISTRERINGSDATUM BETWEEN '" + date1 + "' AND '" + date2 +"'");
                
                    for(HashMap<String, String> alien : sokResultat){
                         txtAreaResultat.append(alien.get("ALIEN_ID") + "\t");
                         txtAreaResultat.append(" " + alien.get("NAMN") + "\n");   
               }    
            } 
            catch(InfException e){
                     JOptionPane.showMessageDialog(null, e.getMessage());
                    }
        }
            else{
                    JOptionPane.showMessageDialog(null, "V�nligen Skriv In Datum I textf�lten!");
                    
         }  
        
    } 
    

    
    
    
    
    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        txtAreaResultat.setText("");
        StringToSQLDateExample();
        
        /*    txtAreaResultat.setText("");
        if(Validering.textNotEmpty(txtDatum1) && Validering.textNotEmpty(txtDatum2)){
            ArrayList<HashMap<String, String>> sokResultat = new ArrayList<HashMap<String, String>>();
            
        try{
            
              String sokRuta1 = txtDatum1.getText();
              SimpleDateFormat datum1 = new SimpleDateFormat("yyyy-MM-dd");
              java.util.Date date = datum1.parse(sokRuta1);
              
              String sokRuta2 = txtDatum2.getText();
              SimpleDateFormat datum2 = new SimpleDateFormat("yyyy-MM-dd");
              java.util.Date date2 = datum2.parse(sokRuta2);
            
              
             String fraga = "SELECT NAMN, ALIEN_ID FROM ALIEN WHERE REGISTRERINGSDATUM BETWEEN " + date + " AND " + date2;
            System.out.println(fraga);
            sokResultat = idb.fetchRows(fraga);
             
              
            for(HashMap<String, String> alien : sokResultat){
                txtAreaResultat.append(alien.get("ALIEN_ID") + "\t");
                txtAreaResultat.append(" " + alien.get("NAMN") + "\n");
            }
        } 
        catch(InfException e){
                     JOptionPane.showMessageDialog(null, e.getMessage());
                     
         }
        catch(ParseException e){
        e.printStackTrace();
   
         throw new RuntimeException(e);
        }
        
        } */
    
    //integer parseint(20180130);
    }//GEN-LAST:event_btnSokActionPerformed

       
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SokAliensMellan2Datum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SokAliensMellan2Datum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SokAliensMellan2Datum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SokAliensMellan2Datum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SokAliensMellan2Datum(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaResultat;
    private javax.swing.JTextField txtDatum1;
    private javax.swing.JTextField txtDatum2;
    // End of variables declaration//GEN-END:variables
}
