/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Validering.Validering;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author marku
 */
public class AndraInfoAgent extends javax.swing.JFrame {
    
    private InfDB idb;
    private String anvandarNamn;
    private Integer agentid;
    
   
    
    public AndraInfoAgent(InfDB idb, String anvandarNamn){
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
        this.anvandarNamn = anvandarNamn;
        listAgent();   //metodanrop
    }
    
    public AndraInfoAgent(InfDB idb) { // sparar idb session f�r denna klass
        initComponents();
        this.idb = idb;
        this.anvandarNamn = anvandarNamn;
        this.setLocationRelativeTo(null);
        listAgent();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAgentID = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAnstallningdatum = new javax.swing.JLabel();
        lblAdministrator = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        txtAgentID = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        Anstallningsdatum = new javax.swing.JTextField();
        txtadmin = new javax.swing.JTextField();
        txtLosenord = new javax.swing.JTextField();
        txtOmrade = new javax.swing.JTextField();
        btnTillbakaAgentInfo = new javax.swing.JButton();
        btnUppdatera = new javax.swing.JButton();
        CBXvaljAgent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Ändra Agent information ");

        lblAgentID.setText("AgentID");

        lblNamn.setText("Namn");

        lblTelefon.setText("Telefon");

        lblAnstallningdatum.setText("Anställningsdatum");

        lblAdministrator.setText("Admininstratör");

        lblLosenord.setText("Lösenord");

        lblOmrade.setText("Område");

        Anstallningsdatum.setText("Ex. 2020-01-06");

        btnTillbakaAgentInfo.setText("Tillbaka");
        btnTillbakaAgentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaAgentInfoActionPerformed(evt);
            }
        });

        btnUppdatera.setText("Uppdatera");
        btnUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraActionPerformed(evt);
            }
        });

        CBXvaljAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valj En Agent:" }));
        CBXvaljAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBXvaljAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnTillbakaAgentInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNamn)
                            .addComponent(lblAgentID)
                            .addComponent(lblTelefon)
                            .addComponent(lblAnstallningdatum)
                            .addComponent(lblAdministrator)
                            .addComponent(lblLosenord)
                            .addComponent(lblOmrade))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Anstallningsdatum)
                            .addComponent(txtOmrade)
                            .addComponent(txtLosenord)
                            .addComponent(txtadmin)
                            .addComponent(txtTelefon)
                            .addComponent(txtNamn)
                            .addComponent(txtAgentID)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUppdatera)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(CBXvaljAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentID)
                    .addComponent(txtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnstallningdatum)
                    .addComponent(Anstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdministrator)
                    .addComponent(txtadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOmrade)
                    .addComponent(txtOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaAgentInfo)
                    .addComponent(btnUppdatera))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(CBXvaljAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listAgent() {
        try{
            ArrayList<HashMap<String, String>> agentLista1 = idb.fetchRows("SELECT AGENT_ID, NAMN FROM AGENT ");
                for(HashMap<String, String> agent : agentLista1) {
                    String allaAgenter = agent.get("AGENT_ID") + " " + agent.get("NAMN");
                        CBXvaljAgent.addItem(allaAgenter);
                  }
             }
        catch(InfException e){
                     JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }
    
    private void CBXvaljAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBXvaljAgentActionPerformed
        Object o = CBXvaljAgent.getSelectedItem();
        String aid = String.valueOf(o);
        
        String agentID = aid.split(" ")[0];
        agentid = Integer.parseInt(agentID);
    }//GEN-LAST:event_CBXvaljAgentActionPerformed

    private void btnUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraActionPerformed
        if (Validering.textFaltHarVarde(txtAgentID) && (Validering.textFaltHarVarde(txtLosenord) && (Validering.textFaltHarVarde(txtNamn) && (Validering.textFaltHarVarde(txtOmrade) && (Validering.textFaltHarVarde(txtTelefon)&& (Validering.textFaltHarVarde(txtadmin))))))) { // validering
            if (Validering.cbValueTrue(CBXvaljAgent)) {
                try {
                    String ettAgentID = txtAgentID.getText();
                    String ettNamn = txtNamn.getText();
                    String ettTelefon = txtTelefon.getText();
                    String ettAnstallningsdatum = Anstallningsdatum.getText();
                    String ettAdmin = txtadmin.getText();
                    String ettOmrade = txtOmrade.getText();
                    //String ettLosenord = idb.fetchSingle("SELECT LOSENORD FROM AGENT WHERE AGENT_ID = " + agentid); // h�mtar nuvarande l�senordet f�r Agent.
                    String ettLosenord = txtLosenord.getText();

                    idb.update("UPDATE AGENT SET AGENT_ID = '" + ettAgentID + "', NAMN = '" + ettNamn
                    + "', TELEFON = '" + ettTelefon + "', ANSTALLNINGSDATUM = '" + ettAnstallningsdatum 
                    + "', ADMINISTRATOR = '" + ettAdmin + "', OMRADE = '" + ettOmrade 
                    + "', LOSENORD = '" + ettLosenord + "' WHERE AGENT_ID = " + agentid); 
                    
                    JOptionPane.showMessageDialog(null, "�ndringen �r registrerad!"); // meddelande n�r uppdateringen registerats.

                } 
                catch (InfException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage()); // fel meddelande
                }
            }
        }
    }//GEN-LAST:event_btnUppdateraActionPerformed

    private void btnTillbakaAgentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaAgentInfoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaAgentInfoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraInfoAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraInfoAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraInfoAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraInfoAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AndraInfoAgent(idb).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Anstallningsdatum;
    private javax.swing.JComboBox<String> CBXvaljAgent;
    private javax.swing.JButton btnTillbakaAgentInfo;
    private javax.swing.JButton btnUppdatera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdministrator;
    private javax.swing.JLabel lblAgentID;
    private javax.swing.JLabel lblAnstallningdatum;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtAgentID;
    private javax.swing.JTextField txtLosenord;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtOmrade;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtadmin;
    // End of variables declaration//GEN-END:variables
}
