/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author khali
 */
public class GeAgentAdminStatus extends javax.swing.JFrame {

    /**
     * Creates new form GeAgentAdminStatus
     */
    private InfDB idb;
    private Integer agentensID;
    
    
    public GeAgentAdminStatus(InfDB idb) {
        initComponents();
        this.idb = idb;
        this.setLocationRelativeTo(null);
        geAgentAdminStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbValjAgentGeAdminStatus = new javax.swing.JComboBox<>();
        lblValjAgentAttGeAdmin = new javax.swing.JLabel();
        btnOKGeAdmin = new javax.swing.JButton();
        btnTillbakaGeAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbValjAgentGeAdminStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj en Agent:" }));
        cmbValjAgentGeAdminStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValjAgentGeAdminStatusActionPerformed(evt);
            }
        });

        lblValjAgentAttGeAdmin.setText("Välj En Agent Att Ge Administatörsstatus:");

        btnOKGeAdmin.setText("OK");
        btnOKGeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKGeAdminActionPerformed(evt);
            }
        });

        btnTillbakaGeAdmin.setText("Tillbaka");
        btnTillbakaGeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaGeAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValjAgentAttGeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbValjAgentGeAdminStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnTillbakaGeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOKGeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblValjAgentAttGeAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbValjAgentGeAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaGeAdmin)
                    .addComponent(btnOKGeAdmin))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geAgentAdminStatus(){
        try{
            ArrayList<HashMap<String, String>> agentLista1 = idb.fetchRows("SELECT AGENT_ID, NAMN FROM AGENT ");
                for(HashMap<String, String> agent1 : agentLista1) {
                    String helaAgentLista1 = agent1.get("AGENT_ID") + " " + agent1.get("NAMN");
                        cmbValjAgentGeAdminStatus.addItem(helaAgentLista1);
                  }
                
             }
                  catch(InfException e){
                     JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }
    
    
    
    private void cmbValjAgentGeAdminStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValjAgentGeAdminStatusActionPerformed
        String enAgent = cmbValjAgentGeAdminStatus.getSelectedItem().toString();
       // String agent1 = String.valueOf(enAgent);
        
        String agentensID1;
        agentensID1 = enAgent.split(" ")[0];
        agentensID = Integer.parseInt(agentensID1);
    }//GEN-LAST:event_cmbValjAgentGeAdminStatusActionPerformed

    private void btnOKGeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKGeAdminActionPerformed
        try{
                  String adminStatus = idb.fetchSingle("SELECT ADMINISTRATOR FROM AGENT WHERE AGENT_ID = " +agentensID);
                  adminStatus = "J";
                  idb.update("UPDATE AGENT SET ADMINISTRATOR = '" +adminStatus+ "' WHERE AGENT_ID = " +agentensID);
                 
            JOptionPane.showMessageDialog(null, "Administratorstatus ändrat!");
                
              
           }catch (InfException e){
            JOptionPane.showMessageDialog(null, e.getMessage()); 
           }
        
    }//GEN-LAST:event_btnOKGeAdminActionPerformed

    private void btnTillbakaGeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaGeAdminActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaGeAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeAgentAdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeAgentAdminStatus(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOKGeAdmin;
    private javax.swing.JButton btnTillbakaGeAdmin;
    private javax.swing.JComboBox<String> cmbValjAgentGeAdminStatus;
    private javax.swing.JLabel lblValjAgentAttGeAdmin;
    // End of variables declaration//GEN-END:variables
}
