/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Validering.Validering;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author erikgoransson
 */
public class TaBortAgent extends javax.swing.JFrame {
    private InfDB idb;
    private String anvandarNamn;
    private Integer agentid;
    /**
     * Creates new form TaBortAgent
     */
    public TaBortAgent(InfDB idb, String anvandarNamn) {
        initComponents();
        this.idb = idb;
        this.anvandarNamn = anvandarNamn;
        this.setLocationRelativeTo(null);
        taBortEnAgent();
    }
    public TaBortAgent (InfDB idb) {
        initComponents();
        this.idb = idb;
        this.anvandarNamn = anvandarNamn;
        this.setLocationRelativeTo(null);
        taBortEnAgent();
    }
    
    public void taBortEnAgent(){ //Lägger till alla agenter i ComboBox listan innan vi kan ta bort en agent.
        try{
            ArrayList<HashMap<String, String>> agentLista1 = idb.fetchRows("SELECT AGENT_ID, NAMN FROM AGENT ");
                for(HashMap<String, String> agent : agentLista1) {
                    String allaAgenter = agent.get("AGENT_ID") + " " + agent.get("NAMN");
                        cmbAgentLista.addItem(allaAgenter);
                  }
             }
        catch(InfException e){
                     JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        cmbAgentLista = new javax.swing.JComboBox<>();
        btnTabort = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setText("Ta bort agent");

        cmbAgentLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj en agent" }));
        cmbAgentLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgentListaActionPerformed(evt);
            }
        });

        btnTabort.setText("Ta bort");
        btnTabort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabortActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(lblRubrik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(cmbAgentLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnTabort)))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblRubrik)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAgentLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTabort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAgentListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgentListaActionPerformed
        Object o = cmbAgentLista.getSelectedItem();
        String aid = String.valueOf(o);
        
        String agentID = aid.split(" ")[0];
        agentid = Integer.parseInt(agentID);
    }//GEN-LAST:event_cmbAgentListaActionPerformed

    private void btnTabortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabortActionPerformed
        if(Validering.cbValueTrue(cmbAgentLista)) {
        try {
            
            String agentNamn = idb.fetchSingle("SELECT NAMN FROM AGENT WHERE AGENT_ID = " + agentid);
            
            idb.update("UPDATE ALIEN SET ANSVARIG_AGENT = NULL WHERE ANSVARIG_AGENT = " + agentid + ";");
            idb.delete("DELETE FROM OMRADESCHEF WHERE AGENT_ID = " + agentid + ";");
            idb.delete("DELETE FROM KONTORSCHEF WHERE AGENT_ID = " + agentid + ";");
            idb.delete("DELETE FROM FALTAGENT WHERE AGENT_ID = " + agentid + ";");
            idb.delete("DELETE FROM INNEHAR_FORDON WHERE AGENT_ID = " + agentid + ";");
            idb.delete("DELETE FROM INNEHAR_UTRUSTNING WHERE AGENT_ID = " + agentid + ";");
 
            idb.delete("DELETE FROM AGENT WHERE AGENT_ID = " + agentid);

            JOptionPane.showMessageDialog(null, "Agent:" + " " + agentNamn + " " + "har raderats från MIB systemet!");

        } 
        catch (InfException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }

    }//GEN-LAST:event_btnTabortActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortAgent(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTabort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cmbAgentLista;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
